# Generated by Django 5.0 on 2024-01-02 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="Invalid Registration Number",
                        message="Enter a valid phone number",
                        regex="^(\\+98|0)?9\\d{9}$",
                    )
                ],
                verbose_name="phone number",
            ),
        ),
    ]
