# Generated by Django 5.0 on 2024-01-02 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_address_user_avatar_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="avatars/%y/%m/%d",
                validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png"])],
                verbose_name="avatar",
            ),
        ),
    ]
