# Generated by Django 5.0 on 2024-01-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="otp code"),
        ),
    ]
